
vagrantIP='127.0.0.1'
ga4ghPort='8080'
keycloakPort='8000'

if ENV['VAGRANT_IP']
   vagrantIP = ENV['VAGRANT_IP']
end
if ENV['KEYCLOAK_PORT']
   keycloakPort = ENV['KEYCLOAK_PORT']
end
if ENV['GA4GH_PORT']
   ga4ghPort = ENV['GA4GH_PORT']
end

#puts "vagrant IP"
#puts vagrantIP

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", guest: keycloakPort, host: keycloakPort
  config.vm.network "forwarded_port", guest: ga4ghPort, host: ga4ghPort

  config.vm.network "private_network", ip: vagrantIP

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  # sync the deployer with the vagrant container
  config.vm.synced_folder "..", "/home/vagrant/candig-deploy"

  # install singularity
  config.vm.provision "shell" do |s|
    s.inline = %Q(

    cd /home/vagrant

    # install tools needed for singularity make
    apt-get update  --fix-missing
    apt-get install -y python dh-autoreconf build-essential squashfs-tools

    # clone & make & install singularity
    git clone https://github.com/singularityware/singularity.git 
    
    cd /home/vagrant/singularity
    ./autogen.sh
    ./configure --prefix=/usr/local --sysconfdir=/etc
    make
    make install

    # create, bootstrap/build singularity ga4gh image and then run container

    cd /home/vagrant/candig-deploy

    # run the deployer script to deploy singularity containers
    python /home/vagrant/candig-deploy/deployer.py -s -i ${1} -kp ${2} -gp ${3} deploy

    )
    s.args = [vagrantIP, keycloakPort, ga4ghPort]
  end

end
