# bootstrap from docker ubuntu image
BootStrap: docker
From: ubuntu:latest

%setup

    echo "%setup"

    # copy files into singularity container root
    cp -r /home/vagrant/ga4gh-server $SINGULARITY_ROOTFS
    cp /home/vagrant/001-ga4gh.conf $SINGULARITY_ROOTFS
    cp /home/vagrant/ports.conf $SINGULARITY_ROOTFS
 
%post

    echo "%post"

    # at this point we're at the root(/) of filesystem in the container

    # install required applications
    apt-get update  --fix-missing

    apt-get install -y tar git curl libcurl4-openssl-dev wget dialog \
    net-tools build-essential python python-dev python-distribute \
    python-pip zlib1g-dev apache2 libapache2-mod-wsgi libxslt1-dev \
    libffi-dev libssl-dev

    # ga4gh server setup
    a2enmod wsgi

    mkdir /var/cache/apache2/python-egg-cache && \
    chown www-data:www-data /var/cache/apache2/python-egg-cache/

    mkdir -p /srv/ga4gh
    # cd /srv/ga4gh

    mv /ga4gh-server /srv/ga4gh/server

    cd /srv/ga4gh/server

    # install python package requirements
    pip install -r requirements.txt

    pip install .

    # ga4gh server setup
    mv /ports.conf /etc/apache2/ports.conf
    mv /001-ga4gh.conf /etc/apache2/sites-available/001-ga4gh.conf
    cp /srv/ga4gh/server/deploy/application.wsgi /srv/ga4gh/application.wsgi
    cp /srv/ga4gh/server/deploy/config.py /srv/ga4gh/config.py

    cd /etc/apache2/sites-enabled
    a2dissite 000-default
    a2ensite 001-ga4gh

    # prepare sample/compliance data
    cd /srv/ga4gh/server
    python scripts/prepare_compliance_data.py -o ../ga4gh-compliance-data

    # ga4gh server configuration

    echo "Singularity-End"

%runscript

    echo '%runscript'
    exec /usr/sbin/apache2ctl start
    echo '%runscript-END'
